### ISSUE TITLE
Set Up Project

### ISSUE THREAD

**Issue by psaegert** [psaegert/Formale-Semantik-Projekt#1]
### TODO

- [x] Join the repository
- [x] Join the slack workspace
- [x] Agree on top 3 topics
- [x] Add an entry in the `Projektgruppen` section
- [x] Add an entry into the meetings spreadsheet
